### ISSUE TITLE
initial compile error on kAXTrustedCheckOptionPrompt

### ISSUE THREAD

**Issue by kangaroo5383** [numist/Switch#21]
```
/Users/jessicalam/Prototype/Switch/Switch/NNAppDelegate.m:77:87: Use of undeclared identifier 'kAXTrustedCheckOptionPrompt'
```

**Comment by numist** [comment]
Are you using the Xcode seed with the latest SDK? That symbol is `CF_AVAILABLE_MAC(10_9)`.

Check _Base SDK_ in the _Build Settings_ tab of the application or project targets and it should be "Latest OS X (OS X 10.9)".

![screen shot 2013-07-18 at 1 08 09](https://f.cloud.github.com/assets/544011/817855/3a07f1b8-ef81-11e2-85cf-d249a1c529d2.png)

**Comment by kangaroo5383** [comment]
I only have 10.8 but it's set to the Latest OS X. 
is 10.9 required?

**Comment by numist** [comment]
The 10.9 SDK is required (because of that build error), but it otherwise builds and runs fine on my 10.8 machine :)

**Comment by numist** [comment]
If you don't have access to the 10.9 SDK and you won't be running your builds on 10.9, it's safe to comment out that line—`isProcessTrustedWithOptions` is `NULL` on 10.8 so that code path will never be taken.
